services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./scripts:/docker-entrypoint-initdb.d
    networks: 
      - greenway
    ports:
      - "5432:5432"
  greenway:
    build: .
    networks: 
      - greenway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
volumes:
  postgres:
    
networks:
  greenway:
    driver: bridge